version: '3.1'

services:

  web:
    build: ${WEB_DOCKER_PATH}
    environment:
      - APACHE_RUN_USER=#1000
    volumes:
      - ${WEB_PATH}:/var/www/html/
    ports:
      - ${WEB_PORT}:80
    working_dir: /var/www/html/

  composer:
    image: composer:1.6
    volumes:
      - ${WEB_PATH}:/var/www/html/
    working_dir: /var/www/html/
    command: composer update --ignore-platform-reqs
